name: End to End Testing

on: [workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Install up K3d
      run: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

    - name: Stand up K3s Cluster
      run: k3d cluster create test-cluster -a 3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
          go-version: 1.23.4

    - name: Run Go tests
      run: |
        go test -v ./...

    - name: Create YAML file
      id: create_yaml
      uses: actions/github-script@v5
      with:
        script: |
          const fs = require('fs');
          const yaml = require('js-yaml');

          const data = {
            internal_dns: [
              { name: "kubernetes.default.svc.cluster.local" }
            ],
            external_dns: [
              { name: "google.com" },
              { name: "bbc.co.uk" }
            ]
          };

          const yamlStr = yaml.dump(data);
          fs.writeFileSync('config.yaml', yamlStr);

    - name: Run Application
      run: | 
        go run ./cmd/main.go
